---

# user to install donkey
donkeycar_user: donkey
donkeycar_user_groups: "dialout,i2c,gpio,spi"

# Clone donkeycar from here
donkeycar_git_repo: "https://github.com/roboracingleague/donkeycar.git"
donkeycar_git_branch: "main"

# Install donkeycar with pip install -e .[{{ donkeycar_flavor }}]
donkeycar_flavor: "pi"

# Install depthai and depthai-sdk
donkeycar_depthai_enabled: false
# Install and enable pigpiod
donkeycar_pigpiod_enabled: false
# Fix for opencv on jetson nano
donkeycar_export_openblas_coretype_armv8: false
# Fix for kerastuner
donkeycar_export_kerastuner_fix: false

# Packages to install with apt
donkeycar_system_packages:
  # pi settings
  # python requirements
  - build-essential
  - python3
  - python3-dev
  - python3-pip
  - python3-setuptools
  - python3-wheel
  # others donkeycar requirements
  #- python3-virtualenv # prefer pip version for ansible
  - python3-numpy
  - python3-picamera
  - python3-pandas
  - python3-rpi.gpio
  - i2c-tools
  - avahi-utils
  - joystick
  - libopenjp2-7-dev
  - libtiff5-dev
  - gfortran
  - libatlas-base-dev
  - libopenblas-dev
  - libhdf5-serial-dev
  - libgeos-dev
  - git
  - ntp
  #- python-smbus
  # opencv requirements
  - libilmbase-dev
  - libopenexr-dev
  - libgstreamer1.0-dev
  #- libjasper-dev # package is missing
  - libwebp-dev
  - libatlas-base-dev
  - libavcodec-dev
  - libavformat-dev
  - libswscale-dev
  #- libqtgui4 # package is missing
  #- libqt4-test # package is missing
  - python3-opencv
  # more
  - python3-psutil # to fix donkeycar install
  - nano
  # serial link debug
  - tio

# Packages to install with pip
donkeycar_pip_packages:
  - tensorflow
  # more
  - tensorflow-io # to remove warning at tensorflow start on pi
