name: donkey
dependencies:
- certifi=14.05.14=py34_0
- freetype=2.5.2=2
- jpeg=8d=0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libtiff=4.0.2=1
- numpy=1.9.2=py34_1
- openblas=0.2.14=1
- openssl=1.0.1k=1
- pillow=2.9.0=py34_0
- pip=7.1.2=py34_0
- python=3.4.3=1
- requests=2.7.0=py34_0
- scipy=0.16.0=np19py34_1
- setuptools=18.1=py34_0
- sqlite=3.8.4.1=1
- tornado=4.2.1=py34_0
- wheel=0.24.0=py34_0
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - adafruit-gpio==1.0.3
  - adafruit-pca9685==1.0.1
  - adafruit-pureio==0.2.1
  - docopt==0.6.2
  - envoy==0.0.3
  - keras==2.0.6
  - picamera==1.13
  - pyyaml==3.12
  - six==1.10.0
  - spidev==3.2
  - theano==0.9.0

