---

- name: update-locale
  command: "update-locale LANG={{ system_locale }}"

- name: restart sshd
  service:
    name: ssh
    state: restarted

- name: reload ufw
  ufw:
    state: reloaded
  when: not ansible_raspbian_testing

- name: reboot host
  reboot:
  when: not ansible_raspbian_testing

# for gantsign.keyboard
- name: reboot host for keyboard
  listen: "dpkg-reconfigure keyboard-configuration"
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 1
    post_reboot_delay: 20
    test_command: whoami
  when: not ansible_raspbian_testing
