---

# TODO python version ?

- name: install python requirements
  apt:
    name:
      - build-essential
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-wheel
    state: present
  tags:
    - python

- name: install python essentials
  pip:
    name:
      - virtualenv
    state: latest
    executable: pip3
  tags:
    - python

# - name: create or update python virtualenv
#   become: false
#   pip:
#     #name:
#     #  - virtualenv
#     #  - pip
#     #  - setuptools
#     #  - wheel
#       #- gdown
#     #state: latest
#     virtualenv: "/home/{{ system_ssh_user }}/env"
#     virtualenv_python: python3
#     virtualenv_site_packages: yes
#   tags:
#     - venv

- name: git clone donkeycar
  become: false
  git:
    repo: "{{ donkeycar_git_repo }}"
    dest: "/home/{{ donkeycar_user }}/donkeycar"
    version: "{{ donkeycar_git_repo_branch }}"
    force: yes
    single_branch: yes
    depth: 1
  tags:
    - clone

- name: create venv and install donkeycar as editable
  become: false
  pip:
    chdir: "/home/{{ donkeycar_user }}/donkeycar"
    name: .[pi]
    virtualenv: "/home/{{ donkeycar_user }}/env"
    extra_args: '-e'
  tags:
    - install

- name: activate venv in bashrc
  lineinfile:
    path: "/home/{{ donkeycar_user }}/.bashrc"
    line: "source env/bin/activate"
    owner: "{{ donkeycar_user }}"
    group: "{{ donkeycar_user }}"
    mode: '0644'
  tags:
    - activate
