---

# TODO python version ?

- name: install system packages
  apt:
    name: "{{ donkeycar_system_packages }}"
    state: present
  tags:
    - apt

# more opencv deps on buster ?! libgtk-3-0

- name: install virtualenv python package for ansible
  pip:
    name: virtualenv # prefer pip version over python3-virtualenv
    state: latest
    executable: pip3
  tags:
    - pip

# specific task to force pip upgrade
- name: create or update python virtualenv
  become: false
  pip:
    name:
      - pip
      - setuptools
      - wheel
    state: latest
    virtualenv: "/home/{{ donkeycar_user }}/env"
    virtualenv_python: python3
    virtualenv_site_packages: yes
  tags:
    - pip

- name: install python requirements
  become: false
  pip:
    name: "{{ donkeycar_pip_packages }}"
    state: latest
    virtualenv: "/home/{{ donkeycar_user }}/env"
  tags:
    - pip

- name: activate venv in bashrc
  lineinfile:
    path: "/home/{{ donkeycar_user }}/.bashrc"
    line: "source env/bin/activate"
    owner: "{{ donkeycar_user }}"
    group: "{{ donkeycar_user }}"
    mode: '0644'
  tags:
    - activate

- name: git clone donkeycar
  become: false
  git:
    repo: "{{ donkeycar_git_repo }}"
    dest: "/home/{{ donkeycar_user }}/donkeycar"
    version: "{{ donkeycar_git_branch }}"
    force: yes
  tags:
    - clone

- name: install donkeycar as editable
  become: false
  pip:
    chdir: "/home/{{ donkeycar_user }}/donkeycar"
    name: .[pi]
    extra_args: '-e'
    virtualenv: "/home/{{ donkeycar_user }}/env"
  tags:
    - editable

- name: test opencv install
  become: false
  shell:
    cmd: "source /home/{{ donkeycar_user }}/env/bin/activate && python -c 'import cv2'"
    executable: /bin/bash
  changed_when: false
  tags:
    - test

- name: test tensorflow install
  become: false
  shell:
    cmd: "source /home/{{ donkeycar_user }}/env/bin/activate && python -c 'import tensorflow'"
    executable: /bin/bash
  changed_when: false
  tags:
    - test
