---

- name: install aptfile
  shell:
    cmd: "curl -o /usr/local/bin/aptfile https://raw.githubusercontent.com/seatgeek/bash-aptfile/master/bin/aptfile && chmod +x /usr/local/bin/aptfile"
    executable: /bin/bash
  tags:
    - aptfile

- name: create donkeycar project directory
  become: false
  file:
    path: "/home/{{ system_ssh_user }}/car"
    state: directory
    mode: '0755'
  tags:
    - project

- name: install python requirements
  apt:
    name:
      - build-essential
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-wheel
    state: present
  tags:
    - python

- name: install python essentials
  pip:
    name:
      - virtualenv
      #- pip
      #- setuptools
      #- wheel
    state: latest
    executable: pip3
  tags:
    - python

- name: create or update python virtualenv
  become: false
  pip:
    #name:
    #  - virtualenv
    #  - pip
    #  - setuptools
    #  - wheel
      #- gdown
    #state: latest
    virtualenv: "/home/{{ system_ssh_user }}/env"
    virtualenv_python: python3
    virtualenv_site_packages: yes
  tags:
    - venv

- name: activate venv in bashrc
  lineinfile:
    path: "/home/{{ system_ssh_user }}/.bashrc"
    line: "source env/bin/activate"
    owner: "{{ system_ssh_user }}"
    group: "{{ system_ssh_user }}"
    mode: '0644'
  tags:
    - venv

- name: git clone donkeycar
  become: false
  git:
    repo: https://github.com/autorope/donkeycar
    dest: "/home/{{ system_ssh_user }}/donkeycar"
    version: main
  tags:
    - donkeycar-repo

- name: install donkeycar repo as python module
  become: false
  shell:
    cmd: "source /home/{{ system_ssh_user }}/env/bin/activate && pip install -e .[pi]"
    chdir: "/home/{{ system_ssh_user }}/donkeycar"
    executable: /bin/bash
  tags:
    - donkeycar-install
