---

- import_tasks: hardware.yml
  tags:
    - hardware

- import_tasks: install.yml
  tags:
    - install



# - name: create donkeycar project directory
#   become: false
#   file:
#     path: "/home/{{ system_ssh_user }}/car"
#     state: directory
#     mode: '0755'
#   tags:
#     - project
