---

- name: create or update python virtualenv
  become: false
  pip:
    name:
      - virtualenv
      - pip
      - setuptools
      - wheel
      - gdown
      - pigpio
      - adafruit-circuitpython-ads1x15
      - adafruit-circuitpython-motor
    state: latest
    virtualenv: "/home/{{ system_ssh_user }}/env"
    virtualenv_python: python3
    virtualenv_site_packages: yes
  tags:
    - venv
    - never



- name: install tensorflow system requirements
  apt:
    name:
      - gfortran
      - libhdf5-dev
      - libc-ares-dev
      - libeigen3-dev
      - libatlas-base-dev
      - libopenblas-dev
      - libblas-dev
      - openmpi-bin
      - libopenmpi-dev
      - liblapack-dev
      - cython
    state: present
  tags:
    - tensorflow
    - never

# split python requirements because /tmp is small, so install big packages one by one
- name: install tensorflow python requirements 1
  become: false
  pip:
    name: grpcio>=1.8.6
    virtualenv: "/home/{{ system_ssh_user }}/env"
  tags:
    - tensorflow
    - never

# split python requirements because /tmp is small, so install big packages one by one
- name: install tensorflow python requirements 2
  become: false
  pip:
    name: scipy==1.4.1
    virtualenv: "/home/{{ system_ssh_user }}/env"
  tags:
    - tensorflow
    - never

# needed ?
- name: install tensorflow python requirements 3
  become: false
  pip:
    name:
      - keras_applications==1.0.8
    extra_args: --no-deps
    virtualenv: "/home/{{ system_ssh_user }}/env"
  tags:
    - tensorflow
    - never

# needed ?
- name: install tensorflow python requirements 4
  become: false
  pip:
    name:
      - mock
      - pybind11
    virtualenv: "/home/{{ system_ssh_user }}/env"
  tags:
    - tensorflow
    - never

- name: check if tensorflow wheel exists
  stat:
    path: "/home/{{ system_ssh_user }}/tensorflow-2.2.0-cp37-cp37m-linux_armv7l.whl"
  register: tf_wheel
  tags:
    - tensorflow
    - never

- name: download tensorflow
  become: false
  shell:
    cmd: "source /home/{{ system_ssh_user }}/env/bin/activate && gdown https://drive.google.com/uc?id=11mujzVaFqa7R1_lB7q0kVPW22Ol51MPg"
    executable: /bin/bash
  when: not tf_wheel.stat.exists
  tags:
    - tensorflow
    - never

- name: install tensorflow
  become: false
  pip:
    name: "/home/{{ system_ssh_user }}/tensorflow-2.2.0-cp37-cp37m-linux_armv7l.whl"
    virtualenv: "/home/{{ system_ssh_user }}/env"
  tags:
    - tensorflow
    - never


# TODO

# sudo bluetoothctl

# démarrer 8bitDo avec Start+B

# scan on
# ...
# E4:17:D8:64:0D:79 8Bitdo SF30 Pro
# ...
# scan off

# connect E4:17:D8:64:0D:79
# trust E4:17:D8:64:0D:79
# quit

# ls /dev/input/js0

# python manage.py drive --js
# or USE_JOYSTICK_AS_DEFAULT = True