---

- name: install requirements
  apt:
    name:
      - build-essential
      - python3
      - python3-dev
      - python3-pip
      #- python3-virtualenv
      - python3-numpy
      - python3-picamera
      - python3-pandas
      - python3-rpi.gpio
      - i2c-tools
      - avahi-utils
      - joystick
      - libopenjp2-7-dev
      - libtiff5-dev
      - gfortran
      - libatlas-base-dev
      - libopenblas-dev
      - libhdf5-serial-dev
      - libgeos-dev
      - git
      - ntp
      #- python-smbus
    state: present
  tags:
    - donkey-apt-
    - never

- name: install opencv requirements
  apt:
    name:
      - libilmbase-dev
      - libopenexr-dev
      - libgstreamer1.0-dev
      - libjasper-dev
      - libwebp-dev
      - libatlas-base-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libqtgui4
      - libqt4-test
      - python3-opencv
    state: present
  tags:
    - open-cv
    - never

- name: install pigpio
  apt:
    name:
      - pigpio
      - python-pigpio
      - python3-pigpio
    state: present
  tags:
    - pigpio
    - never

- name: install python essentials
  pip:
    name:
      - virtualenv
      - pip
      - setuptools
      - wheel
    state: latest
    executable: pip3
  tags:
    - python
    - never

- name: git clone car repo
  become: false
  git:
    repo: git@github.com:rmarret/donkey.git
    dest: "/home/{{ system_ssh_user }}/car"
    version: main
  tags:
    - clone
    
- name: install donkeycar dependencies
  become: false
  shell:
    cmd: "aptfile"
    chdir: "/home/{{ system_ssh_user }}/car"
    executable: /bin/bash
  tags:
    - donkey-apt
    - never


- name: create or update python virtualenv
  become: false
  pip:
    name:
      - virtualenv
      - pip
      - setuptools
      - wheel
      - gdown
      - pigpio
      - adafruit-circuitpython-ads1x15
      - adafruit-circuitpython-motor
    state: latest
    virtualenv: "/home/{{ system_ssh_user }}/env"
    virtualenv_python: python3
    virtualenv_site_packages: yes
  tags:
    - venv
    - never

- name: install donkeycar repo as python module
  become: false
  shell:
    cmd: "source /home/{{ system_ssh_user }}/env/bin/activate && pip install -e .[pi]"
    chdir: "/home/{{ system_ssh_user }}/donkeycar"
    executable: /bin/bash
  tags:
    - venv
    - never

- name: activate venv in bashrc
  lineinfile:
    path: "/home/{{ system_ssh_user }}/.bashrc"
    line: "source env/bin/activate"
    owner: "{{ system_ssh_user }}"
    group: "{{ system_ssh_user }}"
    mode: '0644'
  tags:
    - venv
    - never

- name: enable and start pigpiod
  systemd:
    state: started
    enabled: yes
    name: pigpiod
  tags:
    - pigpio
    - never

- name: install tensorflow system requirements
  apt:
    name:
      - gfortran
      - libhdf5-dev
      - libc-ares-dev
      - libeigen3-dev
      - libatlas-base-dev
      - libopenblas-dev
      - libblas-dev
      - openmpi-bin
      - libopenmpi-dev
      - liblapack-dev
      - cython
    state: present
  tags:
    - tensorflow
    - never

# split python requirements because /tmp is small, so install big packages one by one
- name: install tensorflow python requirements 1
  become: false
  pip:
    name: grpcio>=1.8.6
    virtualenv: "/home/{{ system_ssh_user }}/env"
  tags:
    - tensorflow
    - never

# split python requirements because /tmp is small, so install big packages one by one
- name: install tensorflow python requirements 2
  become: false
  pip:
    name: scipy==1.4.1
    virtualenv: "/home/{{ system_ssh_user }}/env"
  tags:
    - tensorflow
    - never

# needed ?
- name: install tensorflow python requirements 3
  become: false
  pip:
    name:
      - keras_applications==1.0.8
    extra_args: --no-deps
    virtualenv: "/home/{{ system_ssh_user }}/env"
  tags:
    - tensorflow
    - never

# needed ?
- name: install tensorflow python requirements 4
  become: false
  pip:
    name:
      - mock
      - pybind11
    virtualenv: "/home/{{ system_ssh_user }}/env"
  tags:
    - tensorflow
    - never

- name: check if tensorflow wheel exists
  stat:
    path: "/home/{{ system_ssh_user }}/tensorflow-2.2.0-cp37-cp37m-linux_armv7l.whl"
  register: tf_wheel
  tags:
    - tensorflow
    - never

- name: download tensorflow
  become: false
  shell:
    cmd: "source /home/{{ system_ssh_user }}/env/bin/activate && gdown https://drive.google.com/uc?id=11mujzVaFqa7R1_lB7q0kVPW22Ol51MPg"
    executable: /bin/bash
  when: not tf_wheel.stat.exists
  tags:
    - tensorflow
    - never

- name: install tensorflow
  become: false
  pip:
    name: "/home/{{ system_ssh_user }}/tensorflow-2.2.0-cp37-cp37m-linux_armv7l.whl"
    virtualenv: "/home/{{ system_ssh_user }}/env"
  tags:
    - tensorflow
    - never

- name: test opencv install
  become: false
  shell:
    cmd: "source /home/{{ system_ssh_user }}/env/bin/activate && python -c 'import cv2'"
    executable: /bin/bash
  changed_when: false
  tags:
    - opencv
    - never

- name: test tensorflow install
  become: false
  shell:
    cmd: "source /home/{{ system_ssh_user }}/env/bin/activate && python -c 'import tensorflow'"
    executable: /bin/bash
  changed_when: false
  tags:
    - tensorflow
    - never

# TODO
# sudo usermod -aG i2c romain
# sudo usermod -aG gpio romain
# reboot

# sudo bluetoothctl

# démarrer 8bitDo avec Start+B

# scan on
# ...
# E4:17:D8:64:0D:79 8Bitdo SF30 Pro
# ...
# scan off

# connect E4:17:D8:64:0D:79
# trust E4:17:D8:64:0D:79
# quit

# ls /dev/input/js0

# python manage.py drive --js
# or USE_JOYSTICK_AS_DEFAULT = True