---

# Sets the system hostname
system_hostname: "raspberrypi"
# Default user, to use if system_ssh_user does not exists yet
system_default_user: "pi"
system_default_user_password: "raspberry"
# The system password for ansible_user (may be configured as pi).
# NOTE: Should be changed to something secure.
system_ssh_user_password: "{{ vault_system_ssh_user_password }}"
# The password salt to use.
# NOTE: Should be changed to something secure and random.
system_ssh_user_salt: "{{ vault_system_ssh_user_salt }}"
system_ssh_user_sha512_rounds: 5000
system_ssh_user_groups: "adm,dialout,cdrom,sudo,audio,video,plugdev,users,input,netdev"
# The system locale
system_locale: "en_US.UTF-8"
# Generate additionals locales, usefull for remote login with a different locale
system_generate_locales:
  - "fr_FR.UTF-8"
# The system timezone
system_timezone: "Europe/Paris"
# apt-get installs listed packages
system_packages:
  - apt-transport-https
  - vim
  - libsasl2-modules
  - git
  - curl
# Path to default editor
system_default_editor_path: "/usr/bin/vim.basic"

# setup gantsign.keyboard role
keyboard_model: pc104
keyboard_layout: fr

ssh_sshd_config: "/etc/ssh/sshd_config"
# Required field, list of ssh public keys to update ~/.authorized_keys.
# Note: One of these keys needs to be one that Ansible is using.
ssh_public_keys: "{{ vault_ssh_public_keys }}"
# String to present when connecting to host over ssh
ssh_banner:

# UFW rules should always allow SSH to keep Ansible functioning
# Define this in more specific groups
ufw_enabled: true
ufw_rules:
  - {rule: "allow", port: "22", proto: "tcp"}
# Configures if igmp traffic should be allowed
ufw_allow_igmp: true

fail2ban_enabled: true

# Internal variable used when running tests - should not be used.
ansible_raspbian_testing: false
