---

# TODO system_ssh_user_groups
ufw_enabled: false # need different kernel
donkeycar_flavor: "nano"
donkeycar_export_openblas_coretype_armv8: true
donkeycar_export_kerastuner_fix: true

donkeycar_system_packages:
  # nano
  - libhdf5-serial-dev
  - hdf5-tools
  - libhdf5-dev
  - zlib1g-dev
  - zip
  - libjpeg8-dev
  - liblapack-dev
  - libblas-dev
  - gfortran
  - python3-dev
  - python3-pip
  - libxslt1-dev
  - libxml2-dev
  - libffi-dev
  - libcurl4-openssl-dev
  - libssl-dev
  - libpng-dev
  - libopenblas-dev
  - git
  - openmpi-doc
  - openmpi-bin
  - libopenmpi-dev
  # opencv requirements 
  - libilmbase-dev
  - libopenexr-dev
  - libgstreamer1.0-dev
  - libwebp-dev
  - libatlas-base-dev
  - libavcodec-dev
  - libavformat-dev
  - libswscale-dev
  # torch requirements
  - libjpeg-dev
  - zlib1g-dev
  - libpython3-dev
  - libavcodec-dev
  - libavformat-dev
  - libswscale-dev
  # more
  - python3-psutil # to fix donkeycar install
  - nano

donkeycar_pip_packages:
  - testresources
  - futures==2.2.0
  - pybind11
  - cython
  - pyserial
  - future==0.18.0 # version with a wheel instead of 0.18.2
  - mock
  - py-cpuinfo
  - portpicker
  - astor
  - gdown
  - keras_applications # 1.0.8
  # allready in tensorflow 2.7.0 install
  #- protobuf==3.19.6 # 3.12.2
  #- h5py==2.10.0 # no wheel ...
  #- gast==0.4.0 # version for tensorflow-2.7.0
  #- absl-py # 0.9.0
  #- six
  #- requests # 2.24.0
  #- termcolor # 1.1.0
  #- wrapt # 1.12.1
  #- google-pasta # 0.2.0
  #- keras_preprocessing # 1.1.2
  # more from install script
  - numpy==1.19.5
  - scipy
  - pandas
  - pkgconfig
  - packaging
  # tensorflow and torch
  - https://developer.download.nvidia.com/compute/redist/jp/v461/tensorflow/tensorflow-2.7.0+nv22.1-cp36-cp36m-linux_aarch64.whl
  #- https://developer.download.nvidia.com/compute/redist/jp/v461/pytorch/torch-1.11.0a0+17540c5+nv22.01-cp36-cp36m-linux_aarch64.whl
  - torch
  # opencv
  - opencv-python
