---

- name: update apt cache
  apt:
    cache_valid_time: 3600
  tags:
    - apt-upgrade
    - apt-cache

- name: upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  tags:
    - apt-upgrade

- name: install system packages
  apt:
    name: "{{ system_packages }}"
    state: present
  tags:
    - apt-install
