---

- name: list all known variables and facts
  debug:
    var: hostvars[inventory_hostname]
  tags:
    - never
    - debug

- name: check if host is reachable with user and key
  command: /bin/true
  ignore_unreachable: true
  register: command_result
  changed_when: False
  tags:
    - init-user

- name: display help message for default user and password
  debug:
    msg: "host is unreachable with user and key ; trying to connect with 'system_default_user' and 'system_default_user_password' ; use -e 'system_default_user_password=XXX' to override if different from config"
  when: command_result.stdout is undefined
  tags:
    - init-user

- name: connect with default user
  import_tasks: ssh-user.yml
  when: command_result.stdout is undefined
  vars:
    ansible_user: "{{ system_default_user }}"
    ansible_ssh_pass: "{{ system_default_user_password }}"
    ansible_become_password: "{{ system_default_user_password }}"
  tags:
    - init-user
