---

- name: get pi user info
  getent:
    database: passwd
    key: pi
    fail_key: false
  tags:
    - pi-info

- name: advise if pi user exists
  debug:
    msg: "pi user is present"
  when: ansible_facts.getent_passwd.pi
  tags:
    - pi-info

- name: change pi user password
  user:
    name: "pi"
    password: "{{ system_ssh_user_password|password_hash('sha512', system_ssh_user_salt, rounds=system_ssh_user_sha512_rounds) }}"
    update_password: always
    state: present
  when: ansible_facts.getent_passwd.pi is defined and ansible_facts.getent_passwd.pi and system_ssh_user_password is defined and system_ssh_user_salt is defined and system_ssh_user_sha512_rounds is defined
