---

- name: "{{ 'install' if ufw_enabled else 'uninstall' }} ufw"
  apt:
    package: ufw
    state: "{{ 'present' if ufw_enabled else 'absent' }}"
  register: ufw_install

# reboot now to fix "ERROR: Couldn't determine iptables version"
- name: reboot host for ufw
  reboot:
  when: ufw_install.changed

- name: configure ufw defaults
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  with_items:
    - { direction: "incoming", policy: "deny" }
    - { direction: "outgoing", policy: "allow" }
  when: ufw_enabled and ufw_rules|length > 0
  notify:
    - reload ufw

- name: allow IGMP {{ ufw_allow_igmp }}
  blockinfile:
    dest: /etc/ufw/before.rules
    insertbefore: ^# don't delete the 'COMMIT' line or these rules won't be processed
    block: |
      # allow IGMP
      -A ufw-before-input -p igmp -d 224.0.0.0/4 -j ACCEPT
      -A ufw-before-output -p igmp -d 224.0.0.0/4 -j ACCEPT
    state: present
  when: ufw_enabled and ufw_allow_igmp|bool
  notify:
    - reload ufw

- name: configure ufw rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    from_ip: "{{ item.from_ip|default('any') }}"
  with_items:
    - "{{ ufw_rules }}"
  when: ufw_enabled and ufw_rules|length > 0
  notify:
    - reload ufw

- name: enable ufw
  ufw:
    state: enabled
  when: ufw_enabled and not ansible_raspbian_testing
