---

- name: test opencv install
  become: false
  shell:
    cmd: "source /home/{{ donkeycar_user }}/env/bin/activate && python -c 'import cv2'"
    executable: /bin/bash
  changed_when: false

- name: test tensorflow install
  become: false
  shell:
    cmd: "source /home/{{ donkeycar_user }}/env/bin/activate && python -c 'import tensorflow'"
    executable: /bin/bash
  changed_when: false
