---

- name: change pi user password
  user:
    name: "pi"
    password: "{{ system_ssh_user_password|password_hash('sha512', system_ssh_user_salt, rounds=system_ssh_user_sha512_rounds) }}"
    update_password: always
    state: present
  when: system_ssh_user_password is defined and system_ssh_user_salt is defined and system_ssh_user_sha512_rounds is defined
